services:
  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
      - mongo

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
    ports:
      - '5432:5432'

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: superheroApiLogs
    ports:
      - '27017:27017'

volumes:
  db_data:
  mongo_data:

